[project]
name = "bast3st"
version = "0.1.1a1"
description = "Specification of unit tests of .sb3-programs for a Bast3St server"
readme = "README.md"
requires-python = ">=3.14" # t-strings
dependencies = [
    "requests>=2.34.2",
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.14",
]
keywords = ["sb3"]

[project.scripts]
bast3st = "bast3st.cli:run"


[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["bast3st", "bast3st.client"]
package-dir = {"" = "src"}

[dependency-groups]
docs = [
    "sphinx>=9.1.0",
    "sphinx-autobuild>=2025.8.25",
    "sphinx-copybutton>=0.5.2",
    "sphinx-rtd-theme>=3.1.0",
]


[project.urls]
Homepage = "https://marcel-scherzinger.github.io/bast3st"
Documentation = "https://marcel-scherzinger.github.io/bast3st"
Repository = "https://github.com/marcel-scherzinger/bast3st"

